# Generated by Django 3.0.7 on 2020-06-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('alpha2', models.CharField(max_length=2, unique=True)),
                ('alpha3', models.CharField(blank=True, max_length=3, null=True, unique=True)),
                ('numeric', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
    ]
