# Generated by Django 3.0.7 on 2020-06-18 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('industry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=255, unique=True)),
                ('long_name', models.CharField(max_length=512, unique=True)),
                ('business_summary', models.TextField()),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_industry', to='industry.Industry')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
