# Generated by Django 3.0.7 on 2020-06-26 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fintrack_be', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('to_email', models.CharField(blank=True, max_length=255, null=True)),
                ('from_email', models.CharField(blank=True, max_length=255, null=True)),
                ('html_template', models.TextField(blank=True, null=True)),
                ('plain_text', models.TextField(blank=True, null=True)),
                ('template_key', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['subject'],
            },
        ),
        migrations.CreateModel(
            name='MailList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('send_time', models.TimeField(blank=True, null=True)),
                ('send_days', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Mail List',
                'verbose_name_plural': 'Mail Lists',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MailListRecipients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('mail_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_mail_list', to='fintrack_be.MailList')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_list_recipient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mail List Recipient',
                'verbose_name_plural': 'Mail List Recipients',
                'ordering': ['mail_list', 'user'],
            },
        ),
        migrations.AddField(
            model_name='maillist',
            name='recipients',
            field=models.ManyToManyField(blank=True, through='fintrack_be.MailListRecipients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maillist',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_list_template', to='fintrack_be.EmailTemplate'),
        ),
        migrations.AddConstraint(
            model_name='maillistrecipients',
            constraint=models.UniqueConstraint(fields=('mail_list', 'user'), name='mail_list_recipient'),
        ),
    ]
