# Generated by Django 3.0.7 on 2020-07-02 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fintrack_be', '0003_auto_20200626_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='is_open',
        ),
    ]
