# Generated by Django 3.0.7 on 2020-06-20 16:23

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=25, unique=True)),
                ('name', models.CharField(max_length=125)),
            ],
            options={
                'verbose_name': 'Index',
                'verbose_name_plural': 'Indices',
            },
        ),
        migrations.CreateModel(
            name='IndexPriceData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('high', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('low', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('open', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('close', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('change', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('change_perc', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_data', to='index.Index')),
            ],
        ),
        migrations.CreateModel(
            name='IndexConstituents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('constituent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Stock')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Index')),
            ],
            options={
                'verbose_name': 'Index Constituents',
                'verbose_name_plural': 'Indices Constituents',
                'db_table': 'index_constituents',
            },
        ),
        migrations.AddField(
            model_name='index',
            name='constituents',
            field=models.ManyToManyField(blank=True, through='index.IndexConstituents', to='stock.Stock'),
        ),
        migrations.AddIndex(
            model_name='indexpricedata',
            index=models.Index(fields=['timestamp', 'index'], name='index_index_timesta_36ff1a_idx'),
        ),
        migrations.AddConstraint(
            model_name='indexpricedata',
            constraint=models.UniqueConstraint(fields=('index', 'timestamp'), name='unique_index_data'),
        ),
        migrations.AddConstraint(
            model_name='indexconstituents',
            constraint=models.UniqueConstraint(fields=('constituent', 'index'), name='index_constituent'),
        ),
    ]
