# Generated by Django 3.0.7 on 2020-06-18 23:07

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('open_date', models.DateTimeField()),
                ('close_date', models.DateTimeField(blank=True, null=True)),
                ('open_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15)),
                ('close_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('result', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15)),
                ('direction', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], default='BUY', max_length=4)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_instrument', to='stock.Stock')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
            },
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['id', 'instrument'], name='position_po_id_bd6d36_idx'),
        ),
    ]
